// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwzenqaavkqwtaxxhtit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3emVucWFhdmtxd3RheHhodGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzA2NzEsImV4cCI6MjA3MjA0NjY3MX0.H7CjaOqsoDOAcTM2tezLzVD9z-cnz3sh3uFOX1djdrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
  global: {
    headers: {
      'X-Client-Info': 'qrcode-canvas-pro@1.0.0'
    }
  }
});

// Add global error handler for auth errors to prevent console spam
if (typeof window !== 'undefined') {
  window.addEventListener('unhandledrejection', (event) => {
    const error = event.reason;
    if (error?.message?.includes('Invalid Refresh Token') || 
        error?.message?.includes('Refresh Token Not Found') ||
        error?.message?.includes('JWT expired')) {
      // Prevent these specific auth errors from spamming the console
      // They're handled by AuthWrapper
      event.preventDefault();
      console.warn('Auth token error (handled by AuthWrapper):', error.message);
    }
  });
}
